## Reinforcement Learning Programming - CSCN 8020 - Assignment 1


Jun He (8903073)     


## Problem 1
### **Pick-and-Place Robot**: Consider using reinforcement learning to control the motion of a robot arm in a repetitive pick-and-place task. If we want to learn movements that are fast and smooth, the learning agent will have to control the motors directly and obtain feedback about the current positions and velocities of the mechanical linkages.Design the reinforcement learning problem as an MDP, define states, actions, rewards with reasoning.

In [1]:
## The states represent different stages in the pick-and-place task
states = ["idle","picking","placing","finished"]
# The actions define the transitions between the states.
actions = ["move-pick","pick","move-place","place"]
# The rewards encourage the agent to complete the task efficiently.
rewards = {"picking":10, "placing":20, "finished":100}
# Define transition probabilities
transitions = {
    "idle":{"move-pick":"picking"},
    "picking":{"pick":"placing"},
    "placing":{"move-place":"finished"},
    "finished":{}
}

In [2]:
state = "picking"
while state != "finished":
    action = list(transitions[state].keys())[0]  
    # Taking the first available action
    ## get next state
    state = transitions.get(state,{}).get(action, state)
    ## get reward
    reward = rewards.get(state, 0)
    print(f"Action: {action}, New State: {state}, Reward: {reward}")


Action: pick, New State: placing, Reward: 20
Action: move-place, New State: finished, Reward: 100


## Problem 2
### 2x2 Gridworld: Consider a 2x2 gridworld with the following characteristics: 
* • State Space (S): s1, s2, s3, s4.
* • Action Space (A): up, down, left, right.
* • Initial Policy (π): For all states, π(up|s) = 1.
* • Transition Probabilities P (s′|s, a):
* – If the action is valid (does not run into a wall), the transition is deterministic.
* – Otherwise, s′ = s.
* • Rewards R(s):
* – R(s1) = 5 for all actions a.
– R(s2) = 10 for all actions a.
– R(s3) = 1 for all actions a.
– R(s4) = 2 for all actions a.

### Tasks
Perform two iterations of Value Iteration for this gridworld environment. Show the step-by-step process
(without code) including policy evaluation and policy improvement. Provide the following for each
iteration:
* • Iteration 1:
1. Show the initial value function (V) for each state.
2. Perform value function updates.
3. Show the updated value function.
* • Iteration 2: Show the value function (V) after the second iteration.

---declare each item need  <br>
--- **State** Space<br>
states = [s<sub>1</sub>,s<sub>2</sub>,s<sub>3</sub>,s<sub>4</sub>]<br>


--- The **actions** <br>
actions = ["Up","Down","Left","Right"]<br>

--- The **rewards** <br>
R(s<sub>1</sub>)=5
R(s<sub>2</sub>)=10
R(s<sub>3</sub>)=1
R(s<sub>4</sub>)=2

--- The **Discount factor** <br>
gamma = 0.9

--- The **Transition Dynamics** <br>
* If an action moves to a valid state → deterministic transition.
* If an action hits a wall → stays in the same state.

--- The **initializing the value function** <br>
V<sub>0</sub>(s<sub>1</sub>) = 0<br>
V<sub>0</sub>(s<sub>2</sub>) = 0<br>
V<sub>0</sub>(s<sub>3</sub>) = 0<br>
V<sub>0</sub>(s<sub>4</sub>) = 0<br>

### iteration 1
--- **update the value function for each state using the Bellman equation**<br>
there are several possible states: <br>
**State 1** <br>
Right : V(s<sub>2</sub>) = 0<br>
Down : V(s<sub>3</sub>) = 0<br>
Left and Up hit walls (stay in s<sub>1</sub>): V(s<sub>1</sub>) = 0<br>
so: V<sub>1</sub>(s<sub>1</sub>) = 5+0.9×0=5 <br>

**State 2** <br>
Left  : V(s<sub>1</sub>) = 0<br>
Down : V(s<sub>4</sub>) = 0<br>
Right and Up hit walls (stay in s<sub>1</sub>): V(s<sub>1</sub>) = 0<br>
so: V<sub>1</sub>(s<sub>2</sub>) = 10+0.9×0=10 <br>

**State 3** <br>
Right : V(s<sub>4</sub>) = 0<br>
Up  : V(s<sub>1</sub>) = 0<br>
Left and Up hit walls (stay in s<sub>1</sub>): V(s<sub>1</sub>) = 0<br>
so: V<sub>1</sub>(s<sub>3</sub>) = 1+0.9×0=1 <br>

**State 4** <br>
Left  : V(s<sub>3</sub>) = 0<br>
Up  : V(s<sub>2</sub>) = 0<br>
Left and Up hit walls (stay in s<sub>1</sub>): V(s<sub>1</sub>) = 0<br>
so: V<sub>1</sub>(s<sub>4</sub>) = 2+0.9×0=2 <br>

### iteration 2 （we update the values again using the new values from Iteration 1.）<br>
there are several possible states: <br>
**State 1** <br>
Right : V<sub>1</sub>(s<sub>2</sub>) = 10<br>
Down : V<sub>1</sub>(s<sub>3</sub>) = 1<br>

so: V<sub>2</sub>(s<sub>1</sub>) = 5+0.9×10=14 <br>

**State 2** <br>
Left  : V<sub>1</sub>(s<sub>1</sub>) = 5<br>
Down : V<sub>1</sub>(s<sub>4</sub>) = 2<br>

so: V<sub>2</sub>(s<sub>2</sub>) = 10+0.9×5=14.5<br>

**State 3** <br>
Right : V<sub>1</sub>(s<sub>4</sub>) = 0<br>
Up  : V<sub>1</sub>(s<sub>1</sub>) = 0<br>

so: V<sub>2</sub>(s<sub>3</sub>) = 1+0.9×5=5.5 <br>

**State 4** <br>
Left  : V<sub>1</sub>(s<sub>3</sub>) = 0<br>
Up  : V<sub>1</sub>(s<sub>2</sub>) = 0<br>

so: V<sub>2</sub>(s<sub>4</sub>) = 2+0.9×10=11 <br>

In [6]:

gamma = 0.9  # Discount factor
V = {"s1": 0, "s2": 0, "s3": 0, "s4": 0}  # Initial values
R = {"s1": 5, "s2": 10, "s3": 1, "s4": 2}  # Rewards

In [ ]:
# using Bellman’s optimality equation to calculate value function for each state


In [9]:
# for _ in range(2):
#     new_V = {}
#     for s in V:
#         new_V[s] = R[s] + gamma * max([V[s] for a in ["up", "down", "left", "right"]])
#     V = new_V
#     print(f"Iteration {_+1} Value Function: {V}")


## Problem 3
### 5x5 Gridworld: In Lecture 3’s programming exercise (here), we explored an MDP based on a 5x5 gridworld and implemented Value Iteration to estimate the optimal state-value function (V∗) and optimal policy (π∗).

### Tasks
#### Task1: Update MDP Code
1. Update the reward function to be a list of reward based on whether the state is terminal, grey,
or a regular state.
2. Run the existing code developed in class and obtain the optimal state-values and optimal policy.
Provide a figures of the gridworld with the obtained V∗ and π∗ (You can manually create a table)

In [21]:
import numpy as np

In [25]:
# Define a larger gridworld for more complex reinforcement learning scenarios
size = 5
V_grid = np.zeros((size, size))  # Initialize value function grid
policy = np.full((size, size), " ")  # Initialize policy grid

# Define rewards
R_grid = np.full((size, size), -1)  # Default reward for non-terminal states
R_grid[4, 4] = 10  # Goal state reward
R_grid[1, 2] = R_grid[3, 0] = R_grid[0, 4] = -5  # Grey states (unfavorable regions)
R_grid

array([[-1, -1, -1, -1, -5],
       [-1, -1, -5, -1, -1],
       [-1, -1, -1, -1, -1],
       [-5, -1, -1, -1, -1],
       [-1, -1, -1, -1, 10]])

In [30]:
def value_iteration(grid, R, gamma=0.9, theta=1e-3):
    """Performs value iteration on the given grid."""
    V = np.zeros_like(grid, dtype=float)
    delta = float("inf")
    while delta > theta:
        delta = 0
        for i in range(grid.shape[0]):
            for j in range(grid.shape[1]):
                v = V[i, j]  # Store old value
                # Get best possible action value based on neighbors
                possible_values = []
                if i > 0:
                    possible_values.append(V[i-1, j])  # Up
                if i < size-1:
                    possible_values.append(V[i+1, j])  # Down
                if j > 0:
                    possible_values.append(V[i, j-1])  # Left
                if j < size-1:
                    possible_values.append(V[i, j+1])  # Right
                
                V[i, j] = R[i, j] + gamma * max(possible_values, default=0)  # Apply Bellman equation
                delta = max(delta, abs(v - V[i, j]))  # Compute update size
    return V

In [31]:
V_grid = value_iteration(V_grid, R_grid)
print("Optimal Value Function:")
print(V_grid)

Optimal Value Function:
[[14.91813735 17.68758951 20.76468156 24.18360341 23.98234307]
 [17.68758951 20.76468156 20.18360341 27.98234307 32.20310876]
 [20.76468156 24.18360341 27.98234307 32.20310876 36.89279788]
 [20.18360341 27.98234307 32.20310876 36.89279788 42.10351809]
 [27.98234307 32.20310876 36.89279788 42.10351809 47.89316629]]


In [32]:
# Define Policy Extraction
def extract_policy(V, size):
    """Extracts the optimal policy from the optimal value function."""
    policy = np.full((size, size), " ")
    actions = ["↑", "↓", "←", "→"]
    directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]
    
    for i in range(size):
        for j in range(size):
            best_action = None
            best_value = -float("inf")
            for action, (di, dj) in zip(actions, directions):
                ni, nj = i + di, j + dj
                if 0 <= ni < size and 0 <= nj < size:
                    if V[ni, nj] > best_value:
                        best_value = V[ni, nj]
                        best_action = action
            if best_action:
                policy[i, j] = best_action
    return policy

In [33]:
# Extract and Display Optimal Policy
optimal_policy = extract_policy(V_grid, size)
print("Optimal Policy:")
print(optimal_policy)


Optimal Policy:
[['↓' '↓' '→' '↓' '↓']
 ['↓' '↓' '↓' '↓' '↓']
 ['→' '↓' '↓' '↓' '↓']
 ['↓' '↓' '↓' '↓' '↓']
 ['→' '→' '→' '→' '↑']]


#### Task 2: Value Iteration Variations
Implement the following variation of value iteration. Confirm that it reaches the same optimal state-
value function and policy.
1. In-Place Value Iteration: Use a single array to store the state values. This means that you
update the value of a state and immediately use that updated value in the subsequent updates.
Deliverables
* • Full code with comments to explain key steps and calculations.
* • Provide the estimated value function for each state.
* • Important: Compare the performance of these variations in terms of optimization time, number of episodes, and provide comments on their computational complexity.

In [34]:
def in_place_value_iteration(grid, R, gamma=0.9, theta=1e-3):
    """Performs in-place value iteration using a single array to store state values."""
    V = np.zeros_like(grid, dtype=float)  # Initialize value function
    delta = float("inf")
    
    while delta > theta:
        delta = 0
        for i in range(grid.shape[0]):
            for j in range(grid.shape[1]):
                v_old = V[i, j]  # Store old value before update
                
                # Get best possible action value based on neighbors
                possible_values = []
                if i > 0:
                    possible_values.append(V[i-1, j])  # Up
                if i < size-1:
                    possible_values.append(V[i+1, j])  # Down
                if j > 0:
                    possible_values.append(V[i, j-1])  # Left
                if j < size-1:
                    possible_values.append(V[i, j+1])  # Right
                
                # Apply Bellman equation in-place
                V[i, j] = R[i, j] + gamma * max(possible_values, default=0)
                
                # Compute maximum change in values
                delta = max(delta, abs(v_old - V[i, j]))
    
    return V

In [35]:
# Run In-Place Value Iteration
V_in_place = in_place_value_iteration(V_grid, R_grid)
print("In-Place Optimal Value Function:")
print(V_in_place)

In-Place Optimal Value Function:
[[14.91813735 17.68758951 20.76468156 24.18360341 23.98234307]
 [17.68758951 20.76468156 20.18360341 27.98234307 32.20310876]
 [20.76468156 24.18360341 27.98234307 32.20310876 36.89279788]
 [20.18360341 27.98234307 32.20310876 36.89279788 42.10351809]
 [27.98234307 32.20310876 36.89279788 42.10351809 47.89316629]]


In [36]:
# Define Policy Extraction
def extract_policy(V, size):
    """Extracts the optimal policy from the optimal value function."""
    policy = np.full((size, size), " ")
    actions = ["↑", "↓", "←", "→"]
    directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]
    
    for i in range(size):
        for j in range(size):
            best_action = None
            best_value = -float("inf")
            for action, (di, dj) in zip(actions, directions):
                ni, nj = i + di, j + dj
                if 0 <= ni < size and 0 <= nj < size:
                    if V[ni, nj] > best_value:
                        best_value = V[ni, nj]
                        best_action = action
            if best_action:
                policy[i, j] = best_action
    return policy

In [38]:
# Extract and Display Optimal Policy for In-Place Value Iteration
optimal_policy_in_place = extract_policy(V_in_place, size)
print("Optimal Policy (In-Place):")
print(optimal_policy_in_place)

Optimal Policy (In-Place):
[['↓' '↓' '→' '↓' '↓']
 ['↓' '↓' '↓' '↓' '↓']
 ['→' '↓' '↓' '↓' '↓']
 ['↓' '↓' '↓' '↓' '↓']
 ['→' '→' '→' '→' '↑']]


In [40]:
# Comparison
import time
#general iteration
start_v = time.time()
V_standard = value_iteration(V_grid, R_grid)
end_v = time.time()
print(end_v)

#i-place iteration
start_iv = time.time()
V_in_place = in_place_value_iteration(V_grid, R_grid)
end_iv = time.time()
print(end_iv)

1738884741.1450758
1738884741.1470912


## Problem 4
### Off-policy Monte Carlo with Importance Sampling: We will use the same environment, states,actions, and rewards in Problem 3.

### Task
Implement the off-policy Monte Carlo with Importance sampling algorithm to estimate the value function for the given gridworld. Use a fixed behavior policy b(a|s) (e.g., a random policy) to generate episodes and a greedy target policy.<br>
**Suggested steps**
1. Generate multiple episodes using the behavior policy b(a|s).
2. For each episode, calculate the returns (sum of discounted rewards) for each state.
3. Use importance sampling to estimate the value function and update the target policy π(a|s).
4. You can assume a specific discount factor (e.g., γ = 0.9) for this problem.
5. Use the same main algorithm implemented in lecture 4 in class.<br>
**Deliverables**
* • Full code with comments to explain key steps and calculations.
* • Provide the estimated value function for each state.
* • Important Compare the estimated value function obtained from Monte Carlo with the one
obtained from Value Iteration in terms of optimization time, number of episodes, computational complexity, and any other aspects you notice.

In [42]:
import matplotlib.pyplot as plt
import random

In [46]:
# Define the environment parameters for the 5x5 Gridworld
size = 5
 # Initialize value function grid
V_mc = np.zeros((size, size)) 
# Initialize policy grid
policy = np.full((size, size), " ")  

In [47]:
def generate_episode(behavior_policy, grid_size, gamma=0.9):
    """Generates an episode using the behavior policy (random policy)."""
    episode = []
    state = (random.randint(0, grid_size-1), random.randint(0, grid_size-1))  # Start at a random state
    while state != (4, 4):  # Until goal state is reached
        action = random.choice(["up", "down", "left", "right"])  # Choose random action
        next_state = (max(0, min(grid_size-1, state[0] + (action == "down") - (action == "up"))),
                      max(0, min(grid_size-1, state[1] + (action == "right") - (action == "left"))))
        reward = -1 if state not in [(1,2), (3,0), (0,4), (4,4)] else (-5 if state in [(1,2), (3,0), (0,4)] else 10)
        episode.append((state, action, reward))
        state = next_state
    return episode

In [48]:
def monte_carlo_importance_sampling(grid_size, episodes=1000, gamma=0.9):
    """Implements off-policy Monte Carlo learning with importance sampling."""
    returns = {s: [] for s in [(i, j) for i in range(grid_size) for j in range(grid_size)]}
    V_mc = np.zeros((grid_size, grid_size), dtype=float)
    C = np.zeros((grid_size, grid_size), dtype=float)  # Cumulative sum of importance weights
    target_policy = np.full((grid_size, grid_size), " ")
    
    for _ in range(episodes):
        episode = generate_episode(policy, grid_size, gamma)
        G = 0
        W = 1
        
        for t in reversed(range(len(episode))):
            state, action, reward = episode[t]
            G = gamma * G + reward
            C[state] += W
            V_mc[state] += (W / C[state]) * (G - V_mc[state])
            if action != "greedy":  # Stop if action is not in greedy policy
                break
            W *= 1 / 0.25  # Update importance weight (assuming behavior policy is uniform random over 4 actions)
    
    return V_mc

In [49]:
# Run Monte Carlo with Importance Sampling
V_mc_importance = monte_carlo_importance_sampling(size)
print("Monte Carlo Estimated Value Function:")
print(V_mc_importance)

Monte Carlo Estimated Value Function:
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  0.  0. -1.  0.]]


In [50]:
# compare the estimated value function obtained from Monte Carlo with the one obtained from Value Iteration in terms of optimization time
start_vi = time.time()
V_vi = value_iteration(V_grid, R_grid)
end_vi = time.time()
print(end_vi)

start_mc = time.time()
V_mc_importance = monte_carlo_importance_sampling(size)
end_mc = time.time()
print(end_mc)

1738886455.5600617
1738886455.6151958
