In this notebook, we will explore the ReLU (Rectified Linear Unit) activation function using PyTorch. We will start with the most basic example and then provide three more examples, each time increasing the level of complexity.

ReLU stands for Rectified Linear Unit. It is one of the most widely used activation functions in deep learning models. The ReLU function is defined as:

$$
ReLU(x) = max(0, x)
$$

This means that any negative input will be set to zero, while positive inputs remain unchanged.

Let's start with some basic examples.
In this example, we will apply the ReLU function to a simple tensor.


In [7]:
import torch
import torch.nn as nn
import torch.nn.functional as F  # Import torch.nn.functional

In [8]:
### Example 1: Basic ReLU
# Basic tensor
x = torch.tensor([-1.0, 0.0, 1.0, 2.0])
# Apply ReLU
y = F.relu(x)
print(y)

tensor([0., 0., 1., 2.])


In [9]:
# Example #2 - 2D tensor
x = torch.tensor([[-1.0, 2.0], [0.0, -3.0]])
# Apply ReLU
y = F.relu(x)
print(y)

tensor([[0., 2.],
        [0., 0.]])


In [10]:
# Example #3 - Define a simple neural network with one ReLU layer
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc = nn.Linear(2, 2)
    
    def forward(self, x):
        x = self.fc(x)
        x = F.relu(x)  # Apply ReLU activation
        return x

# Create an instance of the network
net = SimpleNN()
print(net)
# Example input
x = torch.tensor([[1.0, -1.0], [0.0, 2.0]])
# Forward pass
y = net(x)
print(y)

SimpleNN(
  (fc): Linear(in_features=2, out_features=2, bias=True)
)
tensor([[0.0000, 0.6083],
        [1.4957, 0.7707]], grad_fn=<ReluBackward0>)


In [11]:
# Example #4 - Define a more complex neural network with multiple layers
class ComplexNN(nn.Module):
    def __init__(self):
        super(ComplexNN, self).__init__()
        self.fc1 = nn.Linear(2, 4)
        self.fc2 = nn.Linear(4, 2)
    
    def forward(self, x):
        x = self.fc1(x)
        x = F.relu(x)
        x = self.fc2(x)
        x = F.relu(x)
        return x

# Create an instance of the network
net = ComplexNN()
# Example input
x = torch.tensor([[1.0, -1.0], [0.0, 2.0]])
# Forward pass
y = net(x)
print(y)

tensor([[0., 0.],
        [0., 0.]], grad_fn=<ReluBackward0>)
